-- phpMyAdmin SQL Dump
-- version 2.9.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jul 28, 2010 at 09:02 AM
-- Server version: 5.0.33
-- PHP Version: 5.2.1
--
-- Database: 'rayzz_utf8'
--

-- --------------------------------------------------------

--
-- Table structure for table 'config_data_music'
--

DROP TABLE IF EXISTS config_data_music;
CREATE TABLE config_data_music (
  config_data_id bigint(20) NOT NULL default '0',
  dim1 varchar(100) character set utf8 NOT NULL,
  dim2 varchar(100) character set utf8 NOT NULL,
  dim3 varchar(100) character set utf8 NOT NULL,
  dim4 varchar(100) character set utf8 NOT NULL,
  config_value text character set utf8 NOT NULL,
  config_type enum('Int','Real','String','Boolean','Array','Intwithsymbol','Email','Website') character set utf8 NOT NULL default 'String',
  config_category varchar(100) character set utf8 NOT NULL,
  config_section varchar(100) character set utf8 NOT NULL,
  config_section_order int(11) NOT NULL default '100',
  editable enum('Yes','No') character set utf8 NOT NULL default 'No',
  edit_order int(11) NOT NULL default '999',
  description text character set utf8 NOT NULL,
  help_text text character set utf8 NOT NULL,
  date_added datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

--
-- Dumping data for table 'config_data_music'
--

INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (1, 'admin', 'musics', 'music_auto_activate', '', '1', 'Boolean', 'music_setting', 'General Music settings', 1, 'Yes', 999, 'Allow auto activate of music', 'Allow auto activate of music', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (2, 'admin', 'musics', 'captcha', '', '1', 'Boolean', 'music_setting', 'General Music settings', 1, 'Yes', 999, 'Enable captcha for music comment', 'Enable captcha for music comment', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (3, 'admin', 'musics', 'captcha_method', '', 'honeypot', 'String', 'music_setting', 'General Music settings', 1, 'Yes', 999, 'Captcha method for music comment (''image'' / ''honeypot'' / ''recaptcha'')', 'Captcha method for music comment (''image'' / ''honeypot'' / ''recaptcha'')', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (4, 'admin', 'musics', 'adult_content_view', '', 'Yes', 'String', 'music_setting', 'General Music settings', 1, 'No', 999, 'Display music adult content to members (''Yes'', ''No'', ''Confirmation'')', 'Display music adult content to members (''Yes'', ''No'', ''Confirmation'')', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (5, 'admin', 'musics', 'adult_minimum_age', '', '18', 'Int', 'music_setting', 'General Music settings', 1, 'No', 999, 'Adult minimum age', 'Adult minimum age', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (6, 'admin', 'musics', 'music_manage_count', '', '25', 'Int', 'music_setting', 'General Music settings', 1, 'Yes', 999, 'Count of featured music in index player', 'Count of featured music in index player', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (7, 'admin', 'musics', 'music_artist_feature', '', '0', 'Boolean', 'music_setting', 'Artist Settings', 2, 'No', 999, 'Allow signup as a artist', 'Allow signup as a artist', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (8, 'admin', 'musics', 'allow_only_artist_to_upload', '', '0', 'Boolean', 'music_setting', 'Artist Settings', 2, 'No', 999, 'Allow only artist to upload music(Applicable only when artist signup is on)', 'Allow only artist to upload music(Applicable only when artist signup is on)', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (9, 'admin', 'musics', 'allowed_usertypes_to_upload_for_sale', '', 'None', 'String', 'music_setting', 'Artist Settings', 2, 'No', 999, 'Allowed type to upload the music for sale (''All'', ''Artist'', ''Listener'', ''None'')', 'Allowed type to upload the music for sale (''All'', ''Artist'', ''Listener'', ''None'')', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (10, 'admin', 'musics', 'allow_members_to_choose_the_preview', '', '0', 'Boolean', 'music_setting', 'Artist Settings', 2, 'No', 999, 'Allow members to choose preview(Applicable only when allowed to mark for sale)', 'Allow members to choose preview(Applicable only when allowed to mark for sale)', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (11, 'admin', 'musics', 'artist_sub_category', '', '1', 'Boolean', 'music_setting', 'Artist Settings', 2, 'No', 999, 'Display artist sub genre', 'Display artist sub genre', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (12, 'admin', 'musics', 'artist_commission', '', '5', 'Int', 'music_setting', 'Artist Settings', 2, 'No', 999, '% of commission', '% of commission', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (13, 'admin', 'musics', 'minimum_threshold_amount', '', '15', 'Int', 'music_setting', 'Artist Settings', 2, 'No', 999, 'Minimum threshold amount ($)', 'Minimum threshold amount ($)', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (14, 'admin', 'musics', 'chart_between_days', '', '15', 'Int', 'music_setting', 'Artist Settings', 2, 'No', 999, 'Time period in days to calculate the top chart', 'Time period in days to calculate the top chart', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (15, 'admin', 'musics', 'music_top_chart_content', '', 'views', 'String', 'music_setting', 'Artist Settings', 2, 'No', 999, 'Music top chart content type (''sales'' / ''views'')', 'Music top chart content type (''sales'' / ''views'')', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (16, 'admin', 'musics', 'upload_music_multiupload', '', '1', 'Boolean', 'music_setting', 'Music Upload types', 3, 'Yes', 999, 'Allow multi upload', 'Allow multi upload', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (17, 'admin', 'musics', 'upload_music_normalupload', '', '1', 'Boolean', 'music_setting', 'Music Upload types', 3, 'Yes', 999, 'Allow normal upload', 'Allow normal upload', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (18, 'admin', 'musics', 'upload_music_externalupload', '', '1', 'Boolean', 'music_setting', 'Music Upload types', 3, 'Yes', 999, 'Allow external upload', 'Allow external upload', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (19, 'admin', 'musics', 'upload_music_recordaudio', '', '1', 'Boolean', 'music_setting', 'Music Upload types', 3, 'Yes', 999, 'Allow record audio', 'Allow record audio', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (20, 'admin', 'musics', 'default_upload_type', '', 'MultiUpload', 'String', 'music_setting', 'Music Upload types ', 3, 'Yes', 999, 'Default upload type (''MultiUpload'', ''NormalUpload'', ''ExternalUpload'', ''RecordAudio'') - Make sure the given upload type is turned on', 'Default upload type (''MultiUpload'', ''NormalUpload'', ''ExternalUpload'', ''RecordAudio'') - Make sure the given upload type is turned on', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (21, 'admin', 'musics', 'multi_upload_files_limit', '', '10', 'String', 'music_setting', 'Music Upload types', 3, 'Yes', 999, 'Multi upload files limit', 'Multi upload files limit', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (22, 'admin', 'musics', 'capture_second', '', '60', 'Int', 'music_setting', 'Music Upload types', 3, 'Yes', 999, 'Music capture time limit', 'Music capture time limit', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (23, 'admin', 'musics', 'trim_music_start_position', '', '0', 'Int', 'music_setting', 'Preview music settings', 4, 'Yes', 999, 'Trimed music start position', 'Trimed music start position', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (24, 'admin', 'musics', 'trim_music_duration', '', '30', 'Int', 'music_setting', 'Preview music settings', 4, 'Yes', 999, 'Trimed music duration', 'Trimed music duration', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (25, 'admin', 'musics', 'full_length_audio', '', 'All', 'String', 'music_setting', 'Preview music settings', 4, 'Yes', 999, 'Play full length music to (Paid membership feature must be enabled for paid member option) (''All'', ''members'',''paid_members'')', 'Play full length music to (Paid membership feature must be enabled for paid member option) (''All'', ''members'',''paid_members'')', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (26, 'admin', 'musics', 'abitrate', '', '56', 'Int', 'music_setting', 'Other Settings', 5, 'Yes', 999, 'Audio quality setting', 'Audio quality setting', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (27, 'admin', 'musics', 'format_arr', '', 'mp3, wma, ogg, m4a, m4r, flac', 'Array', 'music_setting', 'Other Settings', 5, 'Yes', 999, 'Allowed music formats', 'Allowed music formats', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (28, 'admin', 'musics', 'max_size', '', '10', 'Int', 'music_setting', 'Other Settings', 5, 'Yes', 999, 'Allowed music maximum size (In MB)', 'Allowed music maximum size (In MB)', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (29, 'admin', 'musics', 'sub_category', '', '1', 'Boolean', 'music_setting', 'Other Settings', 5, 'Yes', 999, 'Display sub category', 'Display sub category', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (30, 'admin', 'musics', 'download_option', '', 'true', 'String', 'music_setting', 'Music Download', 6, 'Yes', 999, 'Display download link', 'Display download link', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (31, 'admin', 'musics', 'download_previlages', '', 'All', 'String', 'music_setting', 'Music Download', 6, 'Yes', 999, 'Set download permission (''All'', ''Members'')', 'Set download permission (''All'', ''Members'')', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (32, 'admin', 'musics', 'allow_quick_mixs', '', '1', 'Boolean', 'music_setting', 'Music Download', 6, 'Yes', 999, 'Allow quick mixs', 'Allow quick mixs', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (35, 'admin', 'musics', 'capture_second', '', '60', 'Int', 'music_setting', 'Uploader Settings', 7, 'Yes', 999, 'Record audio time limit', 'Record audio time limit', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (36, 'admin', 'musics', 'embedable', '', '1', 'Boolean', 'music_setting', 'Uploader Settings', 7, 'Yes', 999, 'Allow embedable', 'Allow embedable', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (37, 'admin', 'musics', 'embed_method', '', 'html', 'String', 'music_setting', 'Uploader Settings', 7, 'Yes', 999, 'Embed method for audio player (''script'' / ''html'')', 'Embed method for audio player (''script'' / ''html'')', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (38, 'admin', 'musics', 'related_music_default_content', '', 'User', 'String', 'music_setting', 'Uploader Settings', 7, 'Yes', 999, 'Related music tab default content ("User / Related / Top ")', 'Related music tab default content ("User / Related / Top ")', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (39, 'admin', 'musics', 'recommendedmusic', '', '1', 'Boolean', 'music_setting', 'Index Page Musics Settings', 8, 'No', 999, 'Show recommended musics', 'Show recommended musics', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (40, 'admin', 'musics', 'recommendedmusic_total_record', '', '6', 'Int', 'music_setting', 'Index Page Musics Settings', 8, 'No', 999, 'Total recommended music to display', 'Total recommended music to display', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (41, 'admin', 'musics', 'topratedmusic', '', '1', 'Boolean', 'music_setting', 'Index Page Musics Settings', 8, 'No', 999, 'Show toprated music', 'Show toprated music', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (42, 'admin', 'musics', 'topratedmusic_total_record', '', '6', 'Int', 'music_setting', 'Index Page Musics Settings', 8, 'No', 999, 'Total show toprated to display', 'Total show toprated to display', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (43, 'admin', 'musics', 'newmusic', '', '1', 'Boolean', 'music_setting', 'Index Page Musics Settings', 8, 'No', 999, 'Show new music', 'Show new music', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (44, 'admin', 'musics', 'newmusic_total_record', '', '6', 'Int', 'music_setting', 'Index Page Musics Settings', 8, 'No', 999, 'Total new music to display', 'Total new music to display', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (45, 'admin', 'musics', 'recentlylistenedmusic', '', '1', 'Boolean', 'music_setting', 'Index Page Musics Settings', 8, 'No', 999, 'Show recently listened music', 'Show recently listened music', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (46, 'admin', 'musics', 'recentlylistenedmusic_total_record', '', '6', 'Int', 'music_setting', 'Index Page Musics Settings', 8, 'No', 999, 'Total recently viewed music to display', 'Total recently viewed music to display', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (47, 'admin', 'musics', 'music_block_total_row_record', '', '2', 'Int', 'music_setting', 'Index Page Musics Settings', 8, 'No', 999, 'Total no of row record to display', 'Total no of row record to display', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (48, 'admin', 'musics', 'profile_page_total_music', '', '4', 'Int', 'music_setting', 'Index Page Musics Settings', 8, 'No', 999, 'Total music display in profile', 'Total music display in profile', '0000-00-00 00:00:00');
INSERT INTO config_data_music (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (49, 'admin', 'musics', 'music_category_list_priority', '', '1', 'Boolean', 'music_setting', 'General Music settings', 1, 'Yes', 999, 'List genre by priority', 'List genre by priority', '0000-00-00 00:00:00');
