-- phpMyAdmin SQL Dump
-- version 2.9.2
-- http://www.phpmyadmin.net
-- 
-- Host: localhost
-- Generation Time: Jul 28, 2010 at 09:03 AM
-- Server version: 5.0.33
-- PHP Version: 5.2.1
-- 
-- Database: 'rayzz_utf8'
-- 

-- --------------------------------------------------------

-- 
-- Table structure for table 'config_data_video'
-- 

DROP TABLE IF EXISTS config_data_video;
CREATE TABLE config_data_video (
  config_data_id bigint(20) NOT NULL auto_increment,
  dim1 varchar(100) character set utf8 NOT NULL,
  dim2 varchar(100) character set utf8 NOT NULL,
  dim3 varchar(100) character set utf8 NOT NULL,
  dim4 varchar(100) character set utf8 NOT NULL,
  config_value text character set utf8 NOT NULL,
  config_type enum('Int','Real','String','Boolean','Array','Intwithsymbol','Email','Website','Textarea') character set utf8 NOT NULL default 'String',
  config_category varchar(100) character set utf8 NOT NULL,
  config_section varchar(100) character set utf8 NOT NULL,
  config_section_order int(11) NOT NULL default '100',
  editable enum('Yes','No') character set utf8 NOT NULL default 'No',
  edit_order int(11) NOT NULL default '999',
  description text character set utf8 NOT NULL,
  help_text text character set utf8 NOT NULL,
  date_added datetime NOT NULL,
  PRIMARY KEY  (config_data_id)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

-- 
-- Dumping data for table 'config_data_video'
-- 

INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (1, 'admin', 'videos', 'video_auto_encode', '', '1', 'Boolean', 'video_settings', 'feature', 10, 'Yes', 999, 'Allow auto encode of videos', 'Allow auto encode of videos', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (2, 'admin', 'videos', 'video_auto_activate', '', '1', 'Boolean', 'video_settings', 'feature', 10, 'Yes', 999, 'Allow auto activate of videos', 'Allow auto activate of videos', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (3, 'admin', 'videos', 'allow_quick_links', '', '1', 'Boolean', 'video_settings', 'feature', 10, 'Yes', 999, 'Allow Quick Links', 'Allow Quick Links', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (4, 'admin', 'videos', 'allow_history_links', '', '1', 'Boolean', 'video_settings', 'feature', 10, 'Yes', 999, 'Allow History', 'Allow History', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (5, 'admin', 'videos', 'allow_play_list', '', '1', 'Boolean', 'video_settings', 'feature', 10, 'Yes', 999, 'Allow Play List', 'Allow Play List', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (6, 'admin', 'videos', 'upload_videopage_banner', '', '1', 'Boolean', 'video_settings', 'feature', 10, 'Yes', 999, 'Allow members to Upload banner for view video page', 'Allow members to Upload banner for view video page', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (7, 'admin', 'videos', 'embedable', '', '1', 'Boolean', 'video_settings', 'feature', 10, 'Yes', 999, 'Show embed code for videos', 'Show embed code for videos', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (8, 'admin', 'videos', 'embed_method', '', 'html', 'String', 'video_settings', 'feature', 10, 'Yes', 999, 'Embed Method for Video Player (''script''/''html'')', 'Embed Method for Video Player (''script''/''html'')', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (9, 'admin', 'videos', 'watermark_start_time', '', '00:00:01', 'String', 'video_settings', 'watermark', 11, 'Yes', 999, 'Watermark start time', 'Watermark start time', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (10, 'admin', 'module', 'videos_subscription', '', '0', 'Boolean', 'video settings', 'feature', 10, 'No', 999, 'Enable Subscription Module', 'Enable Subscription Module', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (11, 'admin', 'module', 'videos_content_filter', '', '1', 'Boolean', 'video_settings', 'feature', 10, 'No', 999, 'Video Content Filter', 'Video Content Filter', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (12, 'admin', 'videos', 'rotating_thumbnail_feature', '', '1', 'Boolean', 'video_settings', 'feature', 10, 'Yes', 999, 'Enable Rotating Thumbnail', 'Enable Rotating Thumbnail', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (13, 'admin', 'videos', 'display_link_details_to', '', 'Owner', 'String', 'video_settings', 'feature', 10, 'Yes', 999, 'Display link details to (''All''/''Owner'')', 'Display link details to (''All''/''Owner'')', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (14, 'admin', 'videos', 'watermark_text', '', 'Rayzz', 'String', 'video_settings', 'watermark', 11, 'Yes', 999, 'Watermark text', 'Watermark text', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (15, 'admin', 'videos', 'allow_watermark_in_video', '', '1', 'Boolean', 'video_settings', 'watermark', 11, 'Yes', 999, 'Add Watermark to Videos (Since this requires reencoding, there might be a loss in quality)', 'Add Watermark to Videos (Since this requires reencoding, there might be a loss in quality)', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (16, 'admin', 'videos', 'trim_video_start_time', '', '0', 'Int', 'video_settings', 'preview video', 12, 'Yes', 999, 'Trim video start time (Sec)', 'Trim video start time (Sec)', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (17, 'admin', 'videos', 'trim_video_end_time', '', '20', 'Int', 'video_settings', 'preview video', 12, 'Yes', 999, 'Trim video end time (Sec)', 'Trim video end time (Sec)', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (18, 'admin', 'videos', 'full_length_video', '', 'All', 'String', 'video_settings', 'preview video', 10, 'Yes', 999, 'Display Full length Video to (Paid membership feature must be enabled for paid member option)', 'Display Full length Video to (Paid membership feature must be enabled for paid member option)', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (19, 'admin', 'upload_youtube_flv', '', '', '1', 'Boolean', 'video_settings', 'uploader', 13, 'Yes', 999, 'Allow External upload', 'Allow External upload', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (20, 'admin', 'upload_capture_flv', '', '', '1', 'Boolean', 'video_settings', 'uploader', 13, 'Yes', 999, 'Allow Webcam upload', 'Allow Webcam upload', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (21, 'admin', 'upload_video_embed_code', '', '', '1', 'Boolean', 'video_settings', 'uploader', 13, 'Yes', 999, 'Allow External embed video code', 'Allow External embed video code', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (22, 'admin', 'videos', 'capture_second', '', '60', 'Int', 'video_settings', 'uploader', 13, 'Yes', 999, 'Webcam capture time limit', 'Webcam capture time limit', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (23, 'admin', 'videos', 'format_arr', '', 'mpeg,dat,wmv,avi,mov,mpg,flv', 'Array', 'video_settings', 'uploader', 13, 'Yes', 999, 'Allowed Video Formats', 'Allowed Video Formats', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (24, 'admin', 'videos', 'max_size', '', '32', 'Int', 'video_settings', 'uploader', 13, 'Yes', 999, 'Allowed video maximum size(MB)', 'Allowed video maximum size(MB)', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (25, 'admin', 'videos', 'save_original_file_to_download', '', '1', 'Boolean', 'video_settings', 'video download', 14, 'Yes', 999, 'Save Original File to download', 'Save Original File to download', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (26, 'admin', 'videos', 'video_other_formats_enabled', '', '1', 'Boolean', 'video_settings', 'video download', 14, 'Yes', 999, 'Save other format video File to download', 'Save other format video File to download', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (27, 'admin', 'videos', 'download_option', '', '1', 'Boolean', 'video_settings', 'video download', 14, 'Yes', 999, 'Display download link', 'Display download link', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (28, 'admin', 'videos', 'download_previlages', '', 'All', 'String', 'video_settings', 'video download', 14, 'Yes', 999, 'Set Download Permission', 'Set Download Permission', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (29, 'admin', 'videos', 'adult_content_view', '', 'Confirmation', 'String', 'video_settings', 'video download', 14, 'No', 999, 'Display adult content to members', 'Display adult content to members', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (30, 'admin', 'videos', 'share_captcha', '', '0', 'Boolean', 'video_settings', 'miscellaneous', 15, 'Yes', 999, 'Enable captcha in share video', 'Enable captcha in share video', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (31, 'admin', 'videos', 'share_captcha_method', '', 'image', 'String', 'video_settings', 'miscellaneous', 15, 'Yes', 999, 'Share Video Captcha Method  (Set as ''image'' or ''honeypot'')', 'Share Video Captcha Method  (Set as ''image'' or ''honeypot'')', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (32, 'admin', 'videos', 'captcha', '', '1', 'Boolean', 'video_settings', 'miscellaneous', 15, 'Yes', 999, 'Enable captcha in video Comments', 'Enable captcha in video Comments', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (33, 'admin', 'videos', 'captcha_method', '', 'honeypot', 'String', 'video_settings', 'miscellaneous', 15, 'Yes', 999, 'Comment Captcha Method (Set as ''image'' or ''honeypot'' or ''recaptcha'')', 'Comment Captcha Method (Set as ''image'' or ''honeypot'' or ''recaptcha'')', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (34, 'admin', 'mencoder_thumbnail_command', '', '', '{mplayer_path} {idx} -sstep {sstep} -frames {total_frames} -nosound -vo jpeg:quality=100:outdir={output_file} {source_file}', 'Textarea', 'encode_command', 'thumbnail generation', 17, 'Yes', 999, 'Using Mencoder', 'Using Mencoder', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (35, 'admin', 'mencoder_command_flv', '', '', '{mencoder_path} {source_file} -o {output_file} -of lavf -ovc lavc -oac mp3lame -lavcopts vcodec=flv:vbitrate={vbrate}:autoaspect:mbd=2:mv0:trell:v4mv:cbp:last_pred=3:predia=2:dia=2:precmp=2:cmp=2:subcmp=2:preme=2:turbo:acodec=mp3:abitrate={abrate} {scale} -srate {srate} -af lavcresample={lavcresample}', 'Textarea', 'encode_command', 'mencode_command', 16, 'Yes', 999, 'FLV Command', 'FLV Command', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (36, 'admin', 'mencoder_command_otherformat', '', '', '{mencoder_path} {source_file} -o {output_file} -oac mp3lame -ovc lavc', 'Textarea', 'encode_command', 'mencode_command', 16, 'Yes', 999, 'Otherformat Command', 'Otherformat Command', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (37, 'admin', 'video', 'vbitrate', '', '800', 'Int', 'encode_command', 'other settings', 17, 'Yes', 999, 'Video quality setting (Allowed values: 4-16000)', 'Video quality setting (Allowed values: 4-16000)', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (38, 'admin', 'video', 'abitrate', '', '56', 'Int', 'encode_command', 'other settings', 17, 'Yes', 999, 'Audio quality setting (Allowed values: 32-448)', 'Audio quality setting (Allowed values: 32-448)', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (39, 'admin', 'video', 'vfscale', '', '640:480', 'String', 'encode_command', 'other settings', 17, 'Yes', 999, 'Video screen size (Provide the values in the format: width:height)', 'Video screen size (Provide the values in the format: width:height)', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (40, 'admin', 'video', 'srate', '', '22050', 'String', 'encode_command', 'other settings', 17, 'Yes', 999, 'srate (Possible Values : 11025, 22050, 44100, 48000)', 'srate (Possible Values : 11025, 22050, 44100, 48000)', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (41, 'admin', 'video', 'lavcresample', '', '22050', 'String', 'encode_command', 'other settings', 17, 'Yes', 999, 'lavcresample (Possible Values : 11025, 22050, 44100, 48000)', 'lavcresample (Possible Values : 11025, 22050, 44100, 48000)', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (42, 'admin', 'video', 'oac_lame', '', '0', 'Boolean', 'encode_command', 'other settings', 17, 'Yes', 999, 'Use lame for audio codec (If on, it will be -oac mp3lame or -oac lavc )', 'Use lame for audio codec (If on, it will be -oac mp3lame or -oac lavc )', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (43, 'admin', 'upload_video_use_b_frames', '', '', '1', 'Boolean', 'encode_command', 'other settings', 17, 'Yes', 999, 'Use B Frames', 'Use B Frames', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (44, 'admin', 'videos', 'watermark_end_time', '', '00:00:30', 'String', 'video_settings', 'watermark', 11, 'Yes', 999, 'Watermark end time', 'Watermark end time', '0000-00-00 00:00:00');
INSERT INTO config_data_video (config_data_id, dim1, dim2, dim3, dim4, config_value, config_type, config_category, config_section, config_section_order, editable, edit_order, description, help_text, date_added) VALUES (45, 'admin', 'videos', 'video_category_list_priority', '', '1', 'Boolean', 'video_settings', 'miscellaneous', 15, 'Yes', 999, 'List genre by priority', 'List genre by priority', '0000-00-00 00:00:00');
